### ISSUE TITLE
img support

### ISSUE THREAD

**Issue by gahr61** [Aymkdn/html-to-pdfmake#1]
Hi, 
I need to convert img tag to pdf, someday you will add the element?

**Comment by Aymkdn** [comment]
Yes I could add it someday!

**Comment by Aymkdn** [comment]
I've just published v1.0.3 with `<img>` support .... However you have to provide a base64 encoded content for the image, as explained in [the README](https://github.com/Aymkdn/html-to-pdfmake/blob/master/README.md#img) and as demo'ed in the [example.js file](https://github.com/Aymkdn/html-to-pdfmake/blob/278e07d74639e34133c6d01f1225d15b28c0aff7/example.js#L110)

**Comment by tsiegleauq** [comment]
We might be able to use an URL to a image, rather than the base64 representation, if CORS let's us.

Back in OpenSlides 2(.1 I believe), we used to develop a dynamic solution for images that did not require a _direct_ base64 string. Converting it to OpenSlides 3 is still on my roadmap, but here is how we used to do it:

- pre-scan the HTML document for image-tags and save the sources (as seen [here](https://github.com/OpenSlides/OpenSlides/blob/stable/2.3.x/openslides/motions/static/js/motions/pdf.js#L51))
  - we imply images are an absolute URL. CORS is really a topic here, so don't expect external sources to work just fine.
  - That allows you to handle duplicated images pretty well
-  convert the whole list to base64 (as seen [here](https://github.com/OpenSlides/OpenSlides/blob/stable/2.3.x/openslides/core/static/js/core/pdf.js#L1190))
   - The base64 string will be generated using `Image`-Objects and `canvas`, as seen [here](https://github.com/OpenSlides/OpenSlides/blob/stable/2.3.x/openslides/core/static/js/core/pdf.js#L92) 

In the end we have a list of URL-to-Base64 pairs.
```
{
    url-to-image1: base64-of-image1,
}
```
We then used that to generate the HTML document, that's more-or-less how you are already doing it already, as seen [here](https://github.com/OpenSlides/OpenSlides/blob/stable/2.3.x/openslides/core/static/js/core/pdf.js#L1038)


As you can see, this was another era of JavaScript. Using `async await` functions and `Promise.all` this code could probably be cleaned up a whole lot
