### ISSUE TITLE
Render an empty <p> tag

### ISSUE THREAD

**Issue by JerryKusenberger** [Aymkdn/html-to-pdfmake#158]
Hello,

How can I preserve an empty <p> element? It renders fine in HTML but not once in PDF.
```html
<div><p style="line-height: normal; height:19px;">line1</p><p style="line-height: normal; height:19px;">line2</p><p style="line-height: normal; height:19px;"></p><p style="line-height: normal; height:19px;">line4</p><p style="line-height: normal; height:19px;"></p><p style="line-height: normal; height:19px;">line6</p></div>
```
![image](https://user-images.githubusercontent.com/7504167/201537144-a0c7facd-8b8c-42e4-86c3-b7c195f683c0.png)

**Comment by Aymkdn** [comment]
This kind of styling is not supported.

You may want to use `margin` instead of `height`:
```html
<div>
  <div>line1</div>
  <div style="margin-top:5px">line2</div>
  <div style="margin-top:25px">line4</div>
  <div style="margin-top:50px">line6</div>
</div>
```

Otherwise you can use a `table`:
```html
<table>
  <tr>
    <td style="border:0 none">line1</td>
  </tr>
  <tr>
    <td style="height:38px;vertical-align:middle;border:0 none">line2</td>
  </tr>
  <tr>
    <td style="height:58px;vertical-align:middle;border:0 none">line4</td>
  </tr>
  <tr>
    <td style="height:78px;vertical-align:middle;border:0 none">line6</td>
  </tr>
</div>
```

**Comment by JerryKusenberger** [comment]
The html comes from a rich text editor that I don't have a lot of deep control of. When the user types it creates the <p> tags, not able to change those to div or tables. Any other ideas on how I could add styling to preserve the line height of the <p> tag?

**Comment by Aymkdn** [comment]
You could remove the `line-height:normal` in the generated HTML code (because it blocks the `margin` option in PDFMake), and when the user enters an empty line, you'll have to replace it with a blank space.

So your HTML code should look like the below after transformation:
```html
<div><p style="height:19px;">line1</p><p style="height:19px;">line2</p><p style="height:19px;"> </p><p style="height:19px;">line4</p><p style="height:19px;"> </p><p style="height:19px;">line6</p></div>
```

Then you need to call `html-to-pdfmake` with the [option `defaultStyles`](https://github.com/Aymkdn/html-to-pdfmake#defaultstyles) in order to change the default `p` style:
```json
{
  "defaultStyles": {
    "p": {
      "margin":[0, 0, 0, 19]
    }
  }
}
```

Result:
![image](https://user-images.githubusercontent.com/946315/201542997-e7102929-5014-4e5b-922b-d9ecaacebbe4.png)

I'm not sure it will be perfect… This other solution is to contact the person who created [PDFMake](https://github.com/bpampuch/pdfmake) and ask him how you can define a height for a text.
