### ISSUE TITLE
Parse CSS rules

### ISSUE THREAD

**Issue by phil294** [Aymkdn/html-to-pdfmake#41]
How about parsing CSS so you can omit the `styles` property?
```
{
  content: [
    htmlToPdfmake(`
      <style>
        p {
          color: red;
          transition: margin-left 2s; /* Properties unknown to pdfmake are ignored */
        }
      </style>
      <p>hi</pi>
    `)
  ]
}
```
instead of
```
{
  content: [
    htmlToPdfmake(`
      <p>hi</pi>
    `)
  ],
  styles:{
     red:{
        color:'red'
     }
  }
}
```
Even better, in a browser environment:
```
const el = document.getElementById('my-element')
htmlToPdfmake(el)
```
where `htmlToPdfmake` traverses `el` and all of its children and reads their style properties and transforms them properly.

Does that make sense to you?

As a sidenote, I am somewhat confused why there is no way in any library or browser, to do a simple `pdfBlob = window.printWithoutUserInteraction()`. There are printing previews and the like in place for all browsers, but you cant utilize them with Javascript and without user interaction (?)

This repo is great, thanks for your efforts

**Comment by Aymkdn** [comment]
> Does that make sense to you?

Yes, it makes sense, but it's a lot of effort. I only created this project because I needed it for a work project and nothing existed at that time. Nowadays I don't use it for months. It's why I only accept small/quick requests.

If you have time and resources to do such a thing, feel free, but this is definitively not on my list… So I'll close this issue as I won't fix.

> but you cant utilize them with Javascript and without user interaction (?)

No clue about that… But, yeah, it would make sense to have an API provided by browsers.
