### ISSUE TITLE
Text align and Italic

### ISSUE THREAD

**Issue by rosostolato** [Aymkdn/html-to-pdfmake#8]
It does not handle `text-align` style and `<em>` tag:

`
< p style="text-align: center;">
	<span style="font-size: 14px;"><em><strong>testing...</strong></em></span>
< /p>
`

result:

`
{
  "text":"testing...",
  "bold":true,
  "style":["html-strong","html-em","html-span","html-p"]
}
`

**Comment by Aymkdn** [comment]
I've fixed it in v1.0.6 ... it was actually an issue with nested/cascaded tags.

**Comment by rosostolato** [comment]
That's right... I did not realize that I was running an old version... Thank you for your fast answer!

**Comment by SunnysideAaron** [comment]
I work with @rosostolato and just tried the new fix. when a word is both bold and italic the word still disappears. Lists don't appear to be fixed either. We are trying to use the vue2-editor package for our front end and html-to-pdfmake to generate pdfs.  

I've confirmed we are on v1.0.6 of html-to-pdfmake
input string:
<p>i am <strong>a <em>sentence,</em> see</strong> me <u>roar</u>.</p><p><br></p><ul><li>I'm first list</li><li>first list 2nd item</li></ul><p><br></p><p>new sentence no list</p><p><br></p><ol><li>i'm a list</li><li class="ql-indent-1">I'm sub list</li></ol><p><br></p>

in UI:
![Screen Shot 2019-09-11 at 10 57 17 AM](https://user-images.githubusercontent.com/30310399/64722288-00c18e80-d483-11e9-9e5e-4b248ae44928.png)

generated pdf:
![Screen Shot 2019-09-11 at 10 57 41 AM](https://user-images.githubusercontent.com/30310399/64722325-18991280-d483-11e9-9f50-e75dc5538af0.png)

**Comment by Aymkdn** [comment]
I'll look at this on Saturday. I don't have the time before the weekend... Sorry, guys.

**Comment by SunnysideAaron** [comment]
no worries. thanks for working on it.

**Comment by Aymkdn** [comment]
That should be resolved with v1.0.7

**Comment by SunnysideAaron** [comment]
the italic and bold inside each other now appears fixed. But lists are not displaying at all.

**Comment by Aymkdn** [comment]
Examples?

**Comment by SunnysideAaron** [comment]
<p>Here I am.</p><p><br></p><p>I'm another sentence two lines down. <s>Some strike through.</s></p><p><br></p><ul><li>list item 1</li><li class="ql-indent-1">list item 1.2</li><li>list item 2</li></ul><p><br></p><p><br></p>

this produces 
![Screen Shot 2019-09-17 at 2 18 23 PM](https://user-images.githubusercontent.com/30310399/65080532-5e0f8100-d956-11e9-83ee-0eb485d37a0b.png)

Here is the same output in our UI's text field which uses the vue2-editor package

![Screen Shot 2019-09-17 at 2 19 50 PM](https://user-images.githubusercontent.com/30310399/65080522-59e36380-d956-11e9-83e6-1d6b1798d8db.png)

There are 3 problems:
No strike through
2nd sentence is on line 2 instead of line 3.
Lists aren't displayed at all.

Thank you.
